# @package _global_

train_fn: agents.ppo.train.train

env_name: halfcheetah
training_config:
  num_timesteps: 50000000
  num_evals: 20
  reward_scaling: 1
  episode_length: 1000
  normalize_observations: true
  action_repeat: 1
  unroll_length: 20
  num_minibatches: 32
  num_updates_per_batch: 8
  discounting: 0.95
  learning_rate: 0.0003
  entropy_cost: 0.001
  num_envs: 2048
  batch_size: 512
  seed: 3

wandb:
  name: ppo-${env_name}