# @package _global_

train_fn: agents.ppo.train.train

env_name: pusher
training_config:
  num_timesteps: 50000000
  num_evals: 20
  reward_scaling: 5
  episode_length: 1000
  normalize_observations: true
  action_repeat: 1
  unroll_length: 30
  num_minibatches: 16
  num_updates_per_batch: 8
  discounting: 0.95
  learning_rate: 0.0003
  entropy_cost: 0.01
  num_envs: 2048
  batch_size: 512
  seed: ${seed}

wandb:
  name: ppo-${env_name}