# @package _global_

train_fn: agents.ppo.train.train
env_name: fetch
training_config:
  reward_scaling: 1
  episode_length: 1000
  normalize_observations: true
  action_repeat: 1
  entropy_cost: 0.001
  learning_rate: 0.0003
  discounting: 0.997
  num_envs: 2048
  unroll_length: 20
  batch_size: 512
  num_minibatches: 32
  seed: ${seed}
  num_evals: 200
  num_timesteps: 500000000
  num_updates_per_batch: 4
wandb:
  name: ppo-fetch-500m
