# @package _global_

train_fn: agents.ppo.train.train
env_name: halfcheetah
training_config:
  reward_scaling: 1
  episode_length: 1000
  normalize_observations: true
  action_repeat: 1
  entropy_cost: 0.001
  learning_rate: 0.0003
  discounting: 0.99
  num_envs: 2048
  unroll_length: 5
  batch_size: 512
  num_minibatches: 32
  seed: ${seed}
  num_evals: 100
  num_timesteps: 10000000
  num_updates_per_batch: 8
wandb:
  name: ppo-halfcheetah-10m
