# @package _global_

train_fn: agents.ppo.train.train
env_name: humanoid
training_config:
  reward_scaling: 5
  episode_length: 1000
  normalize_observations: true
  action_repeat: 1
  entropy_cost: 0.001
  learning_rate: 0.0003
  discounting: 0.997
  num_envs: 2048
  unroll_length: 5
  batch_size: 512
  num_minibatches: 4
  seed: 0
  num_evals: 100
  num_timesteps: 10000000
  num_updates_per_batch: 8
wandb:
  name: ppo-humanoid-10m
