# @package _global_

train_fn: agents.sac.train.train
env_name: grasp
training_config:
  total_env_steps: 5242880
  eval_frequency: 131012
  reward_scaling: 30
  episode_length: 1000
  normalize_observations: true
  action_repeat: 1
  learning_rate: 0.0003
  discounting: 0.99
  num_envs: 256
  min_replay_size: 8192
  max_replay_size: 1048576
  batch_size: 512
  grad_updates_per_step: 0.0625
  seed: 0
wandb:
  name: sac-grasp-10m
