# @package _global_

train_fn: agents.sac.train.train
env_name: halfcheetah
training_config:
  reward_scaling: 10
  episode_length: 1000
  normalize_observations: true
  action_repeat: 1
  learning_rate: 0.0006
  discounting: 0.95
  num_envs: 256
  min_replay_size: 8192
  max_replay_size: 1048576
  batch_size: 512
  grad_updates_per_step: 0.25
  seed: 1
  num_evals: 100
  num_timesteps: 5242880
  max_devices_per_host: 1
wandb:
  name: sac-halfcheetah-10m
