wandb_version: 1

exp_name:
  desc: null
  value: c51-CartPole-v1
seed:
  desc: null
  value: 2021
track:
  desc: null
  value: true
wandb_project_name:
  desc: null
  value: JAXRL-baselines
wandb_entity:
  desc: null
  value: sustech-emi-org
capture_video:
  desc: null
  value: false
save_model:
  desc: null
  value: false
upload_model:
  desc: null
  value: false
hf_entity:
  desc: null
  value: ''
agent:
  desc: null
  value: c51
env_id:
  desc: null
  value: CartPole-v1
total_timesteps:
  desc: null
  value: 500000
learning_rate:
  desc: null
  value: 0.00025
num_envs:
  desc: null
  value: 1
n_atoms:
  desc: null
  value: 101
v_min:
  desc: null
  value: -100
v_max:
  desc: null
  value: 100
buffer_size:
  desc: null
  value: 10000
gamma:
  desc: null
  value: 0.99
target_network_frequency:
  desc: null
  value: 500
batch_size:
  desc: null
  value: 128
start_e:
  desc: null
  value: 1
end_e:
  desc: null
  value: 0.05
exploration_fraction:
  desc: null
  value: 0.5
learning_starts:
  desc: null
  value: 10000
train_frequency:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    code_path: code/cleanrl-blines/train.py
    python_version: 3.10.14
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716415674
    t:
      1:
      - 1
      - 12
      - 45
      - 50
      - 55
      2:
      - 1
      - 12
      - 45
      - 50
      - 55
      3:
      - 2
      - 4
      - 13
      - 16
      - 23
      - 34
      - 42
      4: 3.10.14
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
