# @package _global_

train_fn: agents.sac.train.train

env_name: hopper
training_config:
  num_timesteps: 6553600
  num_evals: 20
  reward_scaling: 30
  episode_length: 1000
  normalize_observations: true
  action_repeat: 1
  discounting: 0.997
  learning_rate: 0.0006
  num_envs: 128
  batch_size: 512
  grad_updates_per_step: 64
  max_devices_per_host: 1
  max_replay_size: 1048576
  min_replay_size: 8192
  seed: 1

wandb:
  name: sac-${env_name}