exp_name: "dqn_experiment"  # 这个字段通常从代码文件名动态获取，需要在实际使用时指定
seed: 1
track: false
wandb_project_name: "cleanRL"
wandb_entity: null
capture_video: false
save_model: false
upload_model: false
hf_entity: ""

# Algorithm specific arguments

env_id: CartPole-v1
total_timesteps: 500000
learning_rate: 0.00025
num_envs: 1
buffer_size: 10000
gamma: 0.99
tau: 1.0
target_network_frequency: 500
batch_size: 128
start_e: 1.0
end_e: 0.05
exploration_fraction: 0.5
learning_starts: 10000
train_frequency: 10
